<a href="https://colab.research.google.com/github/MandavaNagasreeKalpana/Amazon_ML_Challenge_2025/blob/main/Analytics_Build_ml_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [63]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.metrics import accuracy_score

In [4]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Healthcare_Data_Preprocessed_FIXED.csv')
data.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,37.0,26.0,111.0,198.0,99.0,72.0,5.5,1.7,1.6,4.4,...,1,2,1,0.0,1.0,False,True,True,False,False
1,37.0,24.0,121.0,199.0,103.0,75.0,4.5,1.9,2.6,5.6,...,1,2,1,2.0,2.0,False,False,True,False,False
2,81.0,27.0,NaN,NaN,100.0,74.0,12.1,2.9,2.6,1.8,...,2,0,0,1.0,0.0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,4.3,1.0,1.7,5.2,...,1,2,1,2.0,0.0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,16.0,5.0,3.4,1.4,...,2,0,2,0.0,2.0,False,True,False,True,False

Removing null values

In [9]:
#To remove null values
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = data.select_dtypes(include=['object', 'bool']).columns

for col in numerical_cols:
    data[col] = data[col].fillna(data[col].mean())

for col in categorical_cols:
    data[col] = data[col].fillna(data[col].mode()[0])
data.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Cholesterol             0
Glucose_Level           0
Heart_Rate              0
Sleep_Hours             0
Exercise_Hours          0
Water_Intake            0
Stress_Level            0
Target                  0
Smoking                 0
Alcohol                 0
Diet                    0
MentalHealth            0
PhysicalActivity        0
MedicalHistory          0
Allergies               0
Diet_Type_Vegan         0
Diet_Type_Vegetarian    0
Blood_Group_AB          0
Blood_Group_B           0
Blood_Group_O           0
dtype: int64

In [13]:
#to convert categorical cols into numerical
data['Diet_Type_Vegan']=data['Diet_Type_Vegan'].astype(int)
data['Diet_Type_Vegetarian']=data['Diet_Type_Vegetarian'].astype(int)
data['Blood_Group_AB']=data['Blood_Group_AB'].astype(int)
data['Blood_Group_B']=data['Blood_Group_B'].astype(int)
data['Blood_Group_O']=data['Blood_Group_O'].astype(int)
data

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,37.0,26.0,111.000000,198.000000,99.0,72.0,5.5,1.7,1.6,4.4,...,1,2,1,0.0,1.0,0,1,1,0,0
1,37.0,24.0,121.000000,199.000000,103.0,75.0,4.5,1.9,2.6,5.6,...,1,2,1,2.0,2.0,0,0,1,0,0
2,81.0,27.0,130.922395,199.193934,100.0,74.0,12.1,2.9,2.6,1.8,...,2,0,0,1.0,0.0,1,0,0,0,0
3,25.0,21.0,150.000000,199.000000,102.0,70.0,4.3,1.0,1.7,5.2,...,1,2,1,2.0,0.0,1,0,0,1,0
4,24.0,26.0,146.000000,202.000000,99.0,76.0,16.0,5.0,3.4,1.4,...,2,0,2,0.0,2.0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,5.0,22.0,109.000000,203.000000,98.0,75.0,6.2,2.2,2.5,4.1,...,0,2,2,1.0,0.0,1,0,1,0,0
9996,94.0,26.0,144.000000,203.000000,96.0,72.0,13.4,3.7,3.0,1.5,...,1,0,1,0.0,2.0,0,1,0,1,0
9997,37.0,23.0,185.000000,198.000000,103.0,72.0,5.3,1.8,2.9,7.0,...,1,0,2,0.0,1.0,1,0,1,0,0
9998,50.0,29.0,166.000000,200.000000,100.0,74.0,8.0,2.4,2.6,3.6,...,2,0,0,1.0,1.0,1,0,1,0,0
9999,69.0,29.0,178.000000,203.000000,100.0,75.0,9.7,3.4,2.6,3.4,...,1,2,1,2.0,0.0,0,0,1,0,0

In [14]:
correlation_with_target = data.corr()['Target'].sort_values(ascending=False)
print("Correlation with Target variable:\n", correlation_with_target)

Correlation with Target variable:
 Target                  1.000000
BMI                     0.372972
Stress_Level            0.059825
Diet_Type_Vegan         0.020333
Blood_Group_B           0.010009
Diet                    0.006986
Alcohol                 0.005755
PhysicalActivity       -0.000247
Blood_Group_AB         -0.000351
MedicalHistory         -0.002680
Blood_Group_O          -0.004939
Diet_Type_Vegetarian   -0.005362
Smoking                -0.010177
Heart_Rate             -0.011886
Allergies              -0.012681
MentalHealth           -0.014942
Glucose_Level          -0.031650
Water_Intake           -0.064578
Exercise_Hours         -0.076514
Sleep_Hours            -0.076700
Age                    -0.246949
Cholesterol            -0.342326
Blood_Pressure         -0.376875
Name: Target, dtype: float64

In [47]:
X=data.drop(columns='Target')
y=data['Target']
print(X.shape)
print(y.shape)

(10000, 22)
(10000,)

In [51]:
import statsmodels.api as sm
X = sm.add_constant(X)

model = sm.Logit(y, X).fit()

model.summary()

Optimization terminated successfully.
         Current function value: 0.661042
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Target   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9986
Method:                           MLE   Df Model:                           13
Date:                Mon, 24 Nov 2025   Pseudo R-squ.:                 0.04632
Time:                        02:14:19   Log-Likelihood:                -6610.4
converged:                       True   LL-Null:                       -6931.5
Covariance Type:            nonrobust   LLR p-value:                8.034e-129
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.8866      0.092      9.659      0.000       0.707       1.067
Age                     -0.0218      0.001    -23.798      0.000      -0.024      -0.020
Smoking                 -0.0191      0.025     -0.755      0.450      -0.069       0.031
Alcohol                  0.0118      0.025      0.465      0.642      -0.038       0.061
Diet                     0.0170      0.025      0.673      0.501      -0.033       0.067
MentalHealth            -0.0348      0.025     -1.387      0.165      -0.084       0.014
PhysicalActivity        -0.0027      0.026     -0.107      0.915      -0.053       0.047
MedicalHistory          -0.0099      0.026     -0.381      0.704      -0.061       0.041
Allergies               -0.0320      0.026     -1.233      0.218      -0.083       0.019
Diet_Type_Vegan          0.1035      0.051      2.043      0.041       0.004       0.203
Diet_Type_Vegetarian     0.0214      0.050      0.424      0.672      -0.078       0.120
Blood_Group_AB          -0.0081      0.059     -0.138      0.890      -0.123       0.107
Blood_Group_B            0.0308      0.058      0.528      0.597      -0.084       0.145
Blood_Group_O            0.0149      0.058      0.255      0.798      -0.100       0.129
========================================================================================
"""

Removing p>0.05(Not significant features)

In [52]:
features_to_remove = model.pvalues[model.pvalues > 0.05].index
print(features_to_remove)

X = X.drop(columns=features_to_remove, axis = 1)

Index(['Smoking', 'Alcohol', 'Diet', 'MentalHealth', 'PhysicalActivity',
       'MedicalHistory', 'Allergies', 'Diet_Type_Vegetarian', 'Blood_Group_AB',
       'Blood_Group_B', 'Blood_Group_O'],
      dtype='object')

In [54]:
X.shape,y.shape

((10000, 3), (10000,))

Removing vif>=4

In [55]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
def calculate_vif(data):
    vif_data = pd.DataFrame()
    vif_data["Variable"] = data.columns
    vif_data["VIF"] = [variance_inflation_factor(data.values, i) for i in range(data.shape[1])]
    return vif_data

calculate_vif(X)

          Variable       VIF
0            const  4.219782
1              Age  1.000003
2  Diet_Type_Vegan  1.000003

In [56]:
if 'const' in X.columns:
    X = X.drop('const', axis = 1)
vif_threshold = 4 # Applying the requested threshold
max_vif = float('inf')
VIF_features_removed = []

# Iterate and remove features until all VIFs are below the threshold
while max_vif > vif_threshold:
    # Calculate VIF for current X
    vif_df = calculate_vif(X)

    # Find the maximum VIF score among remaining features
    max_vif = vif_df["VIF"].max()

    # If the maximum VIF is above the threshold, remove that variable
    if max_vif > vif_threshold:
        remove = vif_df.sort_values("VIF", ascending=False).iloc[0]

        # Drop the identified variable from X
        VIF_features_removed.append(remove["Variable"])
        X.drop(remove["Variable"], axis=1, inplace=True)

# Display the features and their VIFs after the iterative removal
final_vif = calculate_vif(X)
print("Features removed due to high VIF:", VIF_features_removed)
print("\nFinal VIF scores for remaining features:")
print(final_vif.sort_values(by='VIF', ascending=False))

Features removed due to high VIF: []

Final VIF scores for remaining features:
          Variable       VIF
1  Diet_Type_Vegan  1.320532
0              Age  1.320532

In [57]:
X.shape,y.shape

((10000, 2), (10000,))

In [58]:
import statsmodels.api as sm
X = sm.add_constant(X)

model = sm.Logit(y, X).fit()

model.summary()

Optimization terminated successfully.
         Current function value: 0.661322
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Target   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Mon, 24 Nov 2025   Pseudo R-squ.:                 0.04591
Time:                        02:15:48   Log-Likelihood:                -6613.2
converged:                       True   LL-Null:                       -6931.5
Covariance Type:            nonrobust   LLR p-value:                6.100e-139
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.8376      0.044     19.181      0.000       0.752       0.923
Age                -0.0218      0.001    -23.823      0.000      -0.024      -0.020
Diet_Type_Vegan     0.0933      0.044      2.126      0.034       0.007       0.179
===================================================================================
"""

Scaling

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
df_scaled = pd.DataFrame(X_scaled, columns = X.columns)

In [61]:
import statsmodels.api as sm
X = sm.add_constant(X)

model = sm.Logit(y, X).fit()

model.summary()

Optimization terminated successfully.
         Current function value: 0.661322
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Target   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Mon, 24 Nov 2025   Pseudo R-squ.:                 0.04591
Time:                        02:17:55   Log-Likelihood:                -6613.2
converged:                       True   LL-Null:                       -6931.5
Covariance Type:            nonrobust   LLR p-value:                6.100e-139
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.8376      0.044     19.181      0.000       0.752       0.923
Age                -0.0218      0.001    -23.823      0.000      -0.024      -0.020
Diet_Type_Vegan     0.0933      0.044      2.126      0.034       0.007       0.179
===================================================================================
"""

Splitting Data and Model building

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7000, 3), (3000, 3), (7000,), (3000,))

In [65]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [67]:
y_train_pred = log.predict(X_train)
y_test_pred = log.predict(X_test)

In [69]:
from sklearn.metrics import f1_score, classification_report

score_train = f1_score(y_train, y_train_pred)
print('Train F1 score:', score_train)
print('Train Classification Report:\n', classification_report(y_train, y_train_pred))

score_test = f1_score(y_test, y_test_pred)
print('\nTest F1 score:', score_test)
print('Test Classification Report:\n', classification_report(y_test, y_test_pred))

Train F1 score: 0.6237478622037625
Train Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.39      0.47      3501
           1       0.54      0.73      0.62      3499

    accuracy                           0.56      7000
   macro avg       0.57      0.56      0.55      7000
weighted avg       0.57      0.56      0.55      7000


Test F1 score: 0.6455412226584408
Test Classification Report:
               precision    recall  f1-score   support

           0       0.63      0.39      0.48      1500
           1       0.56      0.77      0.65      1500

    accuracy                           0.58      3000
   macro avg       0.59      0.58      0.56      3000
weighted avg       0.59      0.58      0.56      3000